### PR TITLE
chore. update readme

### PR DESCRIPTION
**Pull request by pangolp**
## Important note
- Do not approve the PR, because I want to add it as a coauthor, so it appears in the list of contributors.
- Co-authored-by: M'Dic <joshua.lee.betts@gmail.com>
- Co-authored-by: Nefertumm <nefertumtg@gmail.com>

## Changes Proposed:
- I need to modify the readme file again, because I need to add a little information about the delay of bodies, which is an important issue, and I'll take the opportunity to clean up the readme file a little, but I read your suggestions for possible changes.

## Issues Addressed:

- Closes

### CODE REVIEW

**Comment by pangolp** [comment]
@Kaev It won't let me add you to the review, but give me your opinion too, to see if you think it is correct or if something else needs to be added. Thank you.

**Comment by pangolp** [comment]
Sorry, I'm going to make the changes, because they seem important to me, but feel free to add or make modifications in the future. I had not realized that since the pull request had not been merged, their ideas were not going to be taken into account.

**Comment by Kaev** [comment]
> @Kaev It won't let me add you to the review, but give me your opinion too, to see if you think it is correct or if something else needs to be added. Thank you. I also have to add Nefertum, because he was testing and helping me with some tests, although some things were discarded, he was also collaborating.

All good, i just was a middleman to clarify the credits situation with acidmanifesto. I just made the PR because nobody else did it.

**Comment by pangolp** [comment]
> All good, i just was a middleman to clarify the credits situation with acidmanifesto. I just made the PR because nobody else did it.

I didn't understand anything that was happening this morning when I saw that message. I was missing context. And it also happened to me that I didn't see that I wasn't part of the collaborators (I thought I was). And I also took the opportunity to add him to Nefertum, with whom I had some voice calls, and we did tests... he also sometimes helps me with some things when he has some time.

**Comment by Kaev** [comment]
Best case is you talk to Shin directly, he can explain the situation to you.
I'm sorry for the confusion that my PR created.

**Pull request merged**
